import React from 'react';
import {AbsoluteFill, Audio, Composition, interpolate, Series, staticFile, useCurrentFrame} from 'remotion';
import {Apps} from './scenes/Apps';
import {Detects} from './scenes/Detects';
import {End} from './scenes/End';
import {Memory} from './scenes/Memory';
import {Native} from './scenes/Native';
import {Open} from './scenes/Open';
import {Reading} from './scenes/Reading';
import {DISSOLVE} from './components/Motion';
import {FPS, HEIGHT, WIDTH} from './theme';

const SCENES = [
  {id: 'open', el: <Open />, frames: 150},
  {id: 'native', el: <Native />, frames: 300},
  {id: 'detects', el: <Detects />, frames: 390},
  {id: 'reading', el: <Reading />, frames: 460},
  {id: 'memory', el: <Memory />, frames: 330},
  {id: 'apps', el: <Apps />, frames: 230},
  {id: 'end', el: <End />, frames: 150},
];

// Scenes overlap by one dissolve and the incoming one fades up over the last.
const TOTAL = SCENES.reduce((n, s) => n + s.frames, 0) - DISSOLVE * (SCENES.length - 1);

const Fade: React.FC<{children: React.ReactNode}> = ({children}) => {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, DISSOLVE], [0, 1], {extrapolateRight: 'clamp'});
  return <AbsoluteFill style={{opacity}}>{children}</AbsoluteFill>;
};

// Both tracks are generated by audio/ and are the project's own: score.py writes
// the soundtrack against this edit's grid, vo.py speaks audio/script.json. They
// sit in the composition rather than being muxed on afterwards, so `npm run
// render` is the whole film.
export const LaunchVideo: React.FC = () => (
  <>
    <Audio src={staticFile('score.wav')} />
    <Audio src={staticFile('vo.wav')} volume={0.95} />
  <Series>
    {SCENES.map((s, i) => (
      <Series.Sequence key={s.id} durationInFrames={s.frames} offset={i === 0 ? 0 : -DISSOLVE}>
        <Fade>{s.el}</Fade>
      </Series.Sequence>
    ))}
  </Series>
  </>
);

export const RemotionRoot: React.FC = () => (
  <>
    <Composition id="LaunchVideo" component={LaunchVideo} durationInFrames={TOTAL} fps={FPS} width={WIDTH} height={HEIGHT} />
    {SCENES.map((s) => (
      <Composition key={s.id} id={`scene-${s.id}`} component={() => <AbsoluteFill>{s.el}</AbsoluteFill>} durationInFrames={s.frames} fps={FPS} width={WIDTH} height={HEIGHT} />
    ))}
  </>
);
